from typing import Dict

STORY = {
    1: {
        1: {
            "text": (
                "╔══════════════════════════════╗\n"
                "        CAPÍTULO 1\n"
                "   \"Aquilo que insiste em ser visto\"\n"
                "╚══════════════════════════════╝\n\n"
                "Gaia nunca teve dificuldade com rotina. Na verdade, era exatamente o contrário: ela precisava dela. O despertador tocava sempre no mesmo horário, o quarto permanecia organizado, roupas dobradas com precisão, objetos exatamente onde deveriam estar. Nada fora do padrão. Era assim que funcionava — e era assim que ela funcionava. Porque, quando tudo ao redor se mantém estável, fica mais fácil ignorar o que não está.\n\n"
                "Naquela manhã, não havia nada de diferente. E ainda assim… havia. Gaia abriu os olhos antes do alarme tocar. Não de forma brusca, nem assustada — foi natural demais. Como se algo tivesse despertado ela antes do tempo certo. Ela permaneceu deitada por alguns segundos, olhando para o teto. Não estava pensando, mas também não estava vazia. Era aquela sensação estranha de transição, como estar entre um sonho e a realidade sem saber exatamente em qual dos dois você está.\n\n"
                "O alarme finalmente tocou. Ela desligou sem olhar. O gesto automático. Mas o tempo que ficou parada depois disso… não foi. Gaia se sentou devagar. O quarto estava igual, cada detalhe no lugar, exatamente como deveria. E isso não ajudava. Na verdade, tornava tudo mais evidente. Porque a sensação não vinha de fora — vinha dela.\n\n"
                "Mais tarde, a rotina seguiu. Café sem gosto, movimentos repetidos, pensamentos controlados. A cidade não mudou. A Ordem não mudou. Mas Gaia… percebia mais. Como se algo tivesse sido ajustado em uma frequência que só ela estava ouvindo. Ela caminhava pelo corredor como sempre fazia — passos firmes, olhar direto, sem se distrair. Mas dessa vez, os detalhes não passavam. Uma conversa que parava quando ela se aproximava. Um agente que desviava o olhar rápido demais. Uma porta que demorava meio segundo a mais para fechar. Pequenas coisas. Coisas que não significavam nada. Mas que, juntas, formavam algo.\n\n"
                "Ela parou por um instante na área central. Não por dúvida, mas por reconhecimento. O lugar era o mesmo… mas a sensação não. Foi então que o celular vibrou. Um som simples. Curto. Mas suficiente. Gaia olhou sem pressa, sem urgência — mas com atenção demais para ser casual. A tela estava acesa. Sem nome, sem número. Apenas um arquivo. Ela não tocou imediatamente. Seu olhar ficou preso ali, porque algo naquilo não parecia novo. Parecia… atrasado. Como se já estivesse esperando.\n\n"
                "O nome era curto. Simples. Mas errado. \"Você já viu isso.\"\n\n"
                "O ar ao redor não mudou. Mas a forma como ela respirava… sim. Gaia segurou o celular com mais firmeza. Por um instante, pensou em guardar. Pensou em ignorar. Seguir como sempre fez. Mas algo nela não permitiu. Não dessa vez. Seus dedos se moveram devagar, sem pressa — mas sem hesitação real. Porque, no fundo… ela já tinha decidido.\n\n"
                "Gaia toca o arquivo.\n\n"
                "Digite /continuar"
            ),
            "next": 2,
        },
        2: {
            "text": (
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "O toque acontece — e não há tempo entre ação e resposta. A tela muda imediatamente, sem carregamento, sem transição. Não parece que o arquivo foi aberto… parece que algo foi retomado. Gaia não afasta o olhar. Ela observa, como sempre faz, mas dessa vez não é suficiente. O fundo escuro permanece, sem interface, sem estrutura reconhecível. Não há imagem clara, não há vídeo, não há nada que se encaixe no que deveria ser um arquivo comum. Apenas um ponto de luz no centro da tela. Pequeno. Instável. Vivo o suficiente para não ser ignorado.\n\n"
                "Gaia aperta levemente o celular. Seu olhar não vacila. O ponto se expande lentamente, não rápido, não agressivo — inevitável. Linhas começam a surgir ao redor, formas incompletas, como fragmentos de algo que ainda está sendo montado. E então, palavras. Não aparecem de uma vez. Elas se constroem, como se estivessem sendo escritas naquele instante.\n\n"
                "“Você demorou.”\n\n"
                "Gaia não reage de imediato, mas o corpo dela sim. Uma leve tensão nos ombros, um ajuste involuntário na respiração. Aquilo não faz sentido. Ela acabou de abrir. Não houve atraso, não houve espera — e ainda assim, a sensação é clara. Aquilo não está respondendo ao agora. Está respondendo a algo que já aconteceu.\n\n"
                "A tela pisca por um segundo — talvez menos. Mas é o suficiente. Porque nesse instante, Gaia vê algo além das palavras. Não completamente, não de forma nítida, mas o bastante para reconhecer. Um formato. Um símbolo. Um olho. Incompleto. Como se estivesse sendo desenhado… ou lembrado.\n\n"
                "A imagem estabiliza novamente. As palavras continuam ali, mas agora há mais. Abaixo da frase, outra linha começa a surgir. Mais lenta. Mais pesada. Como se hesitasse em existir.\n\n"
                "“Você ainda está—”\n\n"
                "A frase para. Não se completa. Não desaparece. Fica. Suspensa. Como algo interrompido no meio.\n\n"
                "Gaia inclina levemente a cabeça, o olhar mais atento agora. Mais envolvido. Ela não desvia, mas pensa. Porque agora não é só sobre o que está ali… é sobre o que falta.\n\n"
                "Digite /continuar"
            ),
            "next": 3,
        },
        3: {
            "text": (
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia continua olhando para a tela. A frase incompleta não desaparece. “Você ainda está—” permanece ali, como se não estivesse quebrada… apenas esperando. Não uma ação imediata, não um toque impulsivo — mas uma decisão. O símbolo continua presente, o olho incompleto, imperfeito demais para ser ignorado e preciso demais para ser coincidência.\n\n"
                "A respiração dela se estabiliza. Mais lenta. Mais consciente. Como se cada pequeno movimento precisasse agora ser escolhido, e não apenas acontecer. Ela não está mais reagindo. Está participando.\n\n"
                "A tela pisca novamente, mas dessa vez não falha. Ela se ajusta. A frase se completa.\n\n"
                "“Você ainda está aqui.”\n\n"
                "Não é uma pergunta. Não pede confirmação. É uma constatação.\n\n"
                "Algo reconheceu ela.\n\n"
                "O peso no ambiente muda. Não visivelmente, não de forma que pudesse ser explicada — mas presente o suficiente para ser sentido. Gaia aperta levemente o celular, sem perceber.\n\n"
                "Abaixo da frase, novas palavras surgem. Mais rápidas agora. Mais diretas.\n\n"
                "“Então escolha.”\n\n"
                "Não há botões. Não há interface. Mas há intenção.\n\n"
                "E ela entende.\n\n"
                "Isso não é passivo. Isso exige algo dela.\n\n"
                "Três possibilidades se formam na tela. Não como opções comuns, mas como caminhos.\n\n"
                "❖ O que Gaia faz?\n\n"
                "A) Responder — “Quem está aí?” (tentar entender o que está respondendo)\n\n"
                "B) Encerrar — desligar o celular imediatamente (interromper antes que avance)\n\n"
                "C) Observar — não responder, apenas continuar olhando (ver até onde isso vai sem interferir)\n\n"
                "Digite A, B ou C"
            ),
            "choices": {
                "A": {
                    "text": "Responder — “Quem está aí?” (tentar entender o que está respondendo)",
                    "points": {"investigacao": 2, "emocao": 1},
                    "next": 4,
                },
                "B": {
                    "text": "Encerrar — desligar o celular imediatamente (interromper antes que avance)",
                    "points": {"acao": 2, "vazio": 1},
                    "next": 5,
                },
                "C": {
                    "text": "Observar — não responder, apenas continuar olhando (ver até onde isso vai sem interferir)",
                    "points": {"razao": 2, "investigacao": 1},
                    "next": 6,
                },
            },
            "next": None,
        },
        4: {
            "text": (
                "📖✨ CAPÍTULO 1 — BLOCO 4A\n"
                "“Aquilo que responde de volta”\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia não hesita dessa vez. Seus dedos se movem com precisão, mais firmes do que ela esperava. “Quem está aí?” A mensagem não é digitada — não há teclado, não há campo de texto — mas, ainda assim, ela acontece. Como se a intenção fosse suficiente.\n\n"
                "Por um instante, nada muda. A tela permanece escura, as palavras imóveis. O símbolo continua ali, incompleto, observando sem realmente estar inteiro. Então, a resposta vem. Não surge de uma vez. Ela se forma. Letra por letra. Como se estivesse sendo escrita no mesmo ritmo em que algo pensa.\n\n"
                "“Você já sabe.”\n\n"
                "Gaia sente um leve aperto no peito. Não forte o suficiente para ser medo, mas presente o bastante para não ser ignorado. Ela não lembra. E, ao mesmo tempo… lembra.\n\n"
                "A tela pisca novamente, mais rápido dessa vez. O símbolo se ajusta. Não muda completamente, mas se aproxima de algo mais definido. O olho agora parece… direcionado. Não apenas um desenho. Um foco.\n\n"
                "“Você demorou.”\n\n"
                "A frase se repete. Igual. Mas diferente.\n\n"
                "Agora não soa como erro.\n\n"
                "Soa como cobrança.\n\n"
                "Gaia não desvia o olhar. Mas, pela primeira vez, ela sente que não está apenas observando algo.\n\n"
                "Ela está sendo observada de volta."
            ),
            "next": 7,
        },
        5: {
            "text": (
                "📖✨ CAPÍTULO 1 — BLOCO 4B\n"
                "“Aquilo que não se encerra”\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia reage rápido. Rápido demais para permitir qualquer dúvida crescer. Seus dedos pressionam o botão lateral com força suficiente para encerrar aquilo antes que avance. A tela apaga.\n\n"
                "Escuro.\n\n"
                "Silêncio.\n\n"
                "Por um segundo, tudo volta ao normal. Ou parece voltar.\n\n"
                "Ela solta o ar devagar, sem perceber que estava segurando. O ambiente ao redor continua o mesmo, os sons da Ordem seguem distantes, controlados, previsíveis.\n\n"
                "Então o celular vibra novamente.\n\n"
                "Uma vez.\n\n"
                "Gaia não olha.\n\n"
                "Outra vez.\n\n"
                "Agora mais forte.\n\n"
                "Ela olha.\n\n"
                "A tela acende sozinha.\n\n"
                "Sem toque. Sem comando.\n\n"
                "O arquivo continua aberto.\n\n"
                "Exatamente como antes.\n\n"
                "As mesmas palavras.\n\n"
                "O mesmo símbolo.\n\n"
                "Como se nada tivesse sido interrompido.\n\n"
                "Como se nada pudesse ser.\n\n"
                "“Você ainda está aqui.”\n\n"
                "Não há erro. Não há falha.\n\n"
                "Há… persistência.\n\n"
                "Gaia percebe, lentamente, que desligar não foi uma escolha que aquilo considerou válida."
            ),
            "next": 7,
        },
        6: {
            "text": (
                "📖✨ CAPÍTULO 1 — BLOCO 4C\n"
                "“Aquilo que se revela quando você não interfere”\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia não se move. Nenhuma resposta, nenhum gesto, nenhum impulso de interromper. Ela apenas observa. Como sempre fez. Como aprendeu a fazer.\n\n"
                "O tempo passa. Ou parece passar.\n\n"
                "A tela permanece ativa, mas não estática. Pequenos ajustes acontecem. Detalhes quase invisíveis. O símbolo se desloca levemente, como se estivesse sendo observado de diferentes ângulos ao mesmo tempo.\n\n"
                "A frase continua ali.\n\n"
                "“Você ainda está aqui.”\n\n"
                "Sem mudança.\n\n"
                "Sem pressão.\n\n"
                "Mas também sem desaparecer.\n\n"
                "Então, lentamente, algo novo acontece.\n\n"
                "Não nas palavras.\n\n"
                "Mas na forma.\n\n"
                "O símbolo se altera.\n\n"
                "Não de maneira clara, não o suficiente para ser apontado com certeza — mas o bastante para ser sentido. Como se estivesse… respondendo à ausência de resposta.\n\n"
                "Gaia inclina levemente a cabeça.\n\n"
                "E, nesse instante—\n\n"
                "a tela reage.\n\n"
                "“Você percebeu.”\n\n"
                "A frase surge sem aviso. Direta. Limpa. Definitiva.\n\n"
                "Não é sobre ação.\n\n"
                "É sobre atenção.\n\n"
                "E, pela primeira vez, Gaia entende que não importa o que ela faça… aquilo não está esperando resposta.\n\n"
                "Está avaliando presença."
            ),
            "next": 7,
        },
        7: {
            "text": (
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia não se levanta imediatamente. O corpo permanece parado, mas a mente já não está mais naquele lugar. O celular continua sobre a mesa, silencioso demais para parecer inofensivo. Ela poderia simplesmente voltar ao relatório. Poderia fingir que aquilo foi só mais uma anomalia isolada. A Ordem estava cheia delas. Sempre esteve.\n\n"
                "Mas não era isso.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Dessa vez… não era.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ela passa a mão pelo rosto, apoiando o cotovelo na mesa por um instante. O gesto é simples, quase imperceptível, mas carrega mais peso do que deveria. Porque agora ela não está decidindo o que fazer com um caso.\n\n"
                "Está decidindo o que fazer com algo que envolve ela.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Os olhos dela se movem pelo ambiente novamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Jaser está mais distante, encostado em uma das colunas laterais. Como sempre, parece não fazer parte do centro das coisas, mas também não está fora delas. Ele observa. Não diretamente. Não de forma óbvia. Mas observa.\n\n"
                "Por um segundo, os olhares se cruzam.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Não há reação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Mas há entendimento.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Como se ele percebesse que algo saiu do lugar… mesmo sem saber exatamente o quê.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia desvia primeiro.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Sol está em outra área, cercado por telas. Informações abertas, padrões sendo montados, dados cruzando em uma velocidade que a maioria das pessoas ali não acompanharia. Ele não olha para ela. Não ainda.\n\n"
                "Mas Gaia sabe.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Se algo realmente saiu do padrão…\n\n"
                "Sol já está perto de perceber.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "E então—\n\n"
                "Ikarus.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ele está sentado alguns metros à frente, levemente inclinado sobre um caderno. Não um terminal, não um relatório oficial. Um caderno. Ele escreve devagar, como se cada palavra precisasse existir antes de ser registrada. Não parece distraído. Também não parece focado no ambiente.\n\n"
                "Parece… fora do fluxo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia observa por alguns segundos.\n\n"
                "Mais do que deveria.\n\n"
                "E algo nela se incomoda com isso.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Porque, de todos ali…\n\n"
                "ele é o único que não parece reagir ao que está acontecendo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ou talvez—\n\n"
                "seja o único que já sabe.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia se ajeita na cadeira.\n\n"
                "A decisão começa a se formar.\n\n"
                "Não completamente.\n\n"
                "Mas o suficiente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ela não pode ignorar.\n\n"
                "Isso já está claro.\n\n"
                "A questão não é mais *se* ela vai agir.\n\n"
                "É *como*.\n\n"
                "E, principalmente—\n\n"
                "*com quem.*\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "O celular permanece ali.\n\n"
                "Quieto.\n\n"
                "Mas agora—\n\n"
                "isso não significa segurança.\n\n"
                "Significa espera.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia respira fundo.\n\n"
                "E, pela primeira vez desde que abriu o arquivo…\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "ela percebe.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Isso não é sobre entender o que aconteceu.\n\n"
                "É sobre decidir em quem confiar.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "A) Procurar Jaser\n"
                "B) Procurar Sol\n"
                "C) Procurar Ikarus\n\n"
                "Digite A, B ou C"
            ),
            "choices": {
                "A": {
                    "text": "Procurar Jaser",
                    "points": {"investigacao": 2, "vazio": 1},
                    "next": 8,
                },
                "B": {
                    "text": "Procurar Sol",
                    "points": {"razao": 2, "investigacao": 1},
                    "next": 9,
                },
                "C": {
                    "text": "Procurar Ikarus",
                    "points": {"emocao": 2, "investigacao": 1},
                    "next": 10,
                },
            },
            "next": None,
        },
        8: {
            "text": (
                "📖✨ CAPÍTULO 1 — BLOCO 7A\n"
                "(Escolha Jaser)\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia decide procurar Jaser.\n\n"
                "Não porque confia completamente nele.\n\n"
                "Mas porque ele observa mais do que pergunta.\n\n"
                "E, naquele momento…\n\n"
                "isso parece mais seguro.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser percebe ela se aproximando antes mesmo de levantar o olhar. Não demonstra surpresa. Apenas espera.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Quando Gaia para na frente dele, o silêncio dura alguns segundos.\n\n"
                "Então Jaser fala:\n\n"
                "— “Você viu alguma coisa.”\n\n"
                "Não é pergunta.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente algo estranho nesse instante.\n\n"
                "Como se, pela primeira vez desde o arquivo…\n\n"
                "alguém estivesse olhando para o problema certo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "❖ Efeito:\n"
                "+2 Investigação\n"
                "+1 Vazio"
            ),
            "next": [2, 1],
        },
        9: {
            "text": (
                "📖✨ CAPÍTULO 1 — BLOCO 7B\n"
                "(Escolha Sol)\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia decide procurar Sol.\n\n"
                "Se aquilo é real…\n\n"
                "então existe um padrão.\n\n"
                "E se existe um padrão—\n\n"
                "Sol vai encontrar.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela atravessa a área principal até as mesas de análise. Sol continua cercado por telas e informações, como se o resto do ambiente não existisse.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Quando Gaia chama seu nome, ele finalmente olha para ela.\n\n"
                "Só uma vez.\n\n"
                "E isso já basta.\n\n"
                "— “Algo saiu do comportamento esperado.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia percebe imediatamente:\n\n"
                "ele não perguntou *se* algo aconteceu.\n\n"
                "Perguntou apenas o quanto.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "❖ Efeito:\n"
                "+2 Razão\n"
                "+1 Investigação"
            ),
            "next": [2, 2],
        },
        10: {
            "text": (
                "📖✨ CAPÍTULO 1 — BLOCO 7C\n"
                "(Escolha Ikarus)\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia decide procurar Ikarus.\n\n"
                "A escolha não faz sentido lógico.\n\n"
                "E talvez seja exatamente por isso.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele continua sentado, escrevendo no mesmo caderno, como se o mundo ao redor funcionasse em uma velocidade diferente da dele.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia para ao lado da mesa.\n\n"
                "Ikarus levanta o olhar devagar.\n\n"
                "E, por um instante—\n\n"
                "o ambiente parece silencioso demais.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele fecha o caderno sem pressa.\n\n"
                "Então pergunta:\n\n"
                "— “Você também sentiu?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia não responde imediatamente.\n\n"
                "Porque essa é a primeira vez desde o arquivo…\n\n"
                "que alguém parece entender antes mesmo da explicação existir.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "❖ Efeito:\n"
                "+2 Emoção\n"
                "+1 Investigação"
            ),
            "next": [2, 3],
        },
    },
    2: {
        1: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 1A\n"
                "“Aquilo que é percebido no silêncio” (Rota Jaser)\n"
                "╔══════════════════════════════╗\n"
                "        CAPÍTULO 2\n"
                "  “Aquilo que é percebido no silêncio”\n"
                "╚══════════════════════════════╝\n"
                "Jaser não reage imediatamente quando Gaia se aproxima. Ele continua encostado na coluna, os braços cruzados, o olhar perdido em algum ponto do corredor principal da Ordem. À primeira vista, parece distraído. Mas Gaia percebe rápido: ele nunca está distraído.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela para ao lado dele.\n\n"
                "Por alguns segundos, nenhum dos dois fala.\n\n"
                "Estranhamente, isso não incomoda.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então Jaser quebra o silêncio:\n\n"
                "— “Você viu alguma coisa.”\n\n"
                "Não é pergunta.\n\n"
                "Não há surpresa na voz dele.\n\n"
                "Só certeza.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia demora um instante antes de responder.\n\n"
                "— “Como sabe?”\n\n"
                "Jaser finalmente olha para ela.\n\n"
                "— “Porque você tá olhando pros lugares errados.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela franze levemente a testa.\n\n"
                "Jaser continua:\n\n"
                "— “Quando alguém passa por alguma coisa normal, procura resposta.”\n\n"
                "Uma pausa curta.\n\n"
                "— “Quando passa por alguma coisa errada… procura confirmação.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia não responde.\n\n"
                "Porque ele acertou.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser descruza os braços devagar.\n\n"
                "— “O que aconteceu?”\n\n"
                "Gaia olha rapidamente ao redor antes de pegar o celular. Ela não sabe exatamente por que sente necessidade de ter cuidado. Talvez porque, desde que abriu o arquivo, tudo parece mais sensível. Mais atento.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela mostra a tela.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O símbolo continua lá.\n\n"
                "O olho incompleto.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser perde o foco por meio segundo.\n\n"
                "E isso, vindo dele…\n\n"
                "já é uma reação grande demais.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Onde conseguiu isso?”\n\n"
                "A pergunta vem mais rápida agora.\n\n"
                "Mais séria.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o estômago apertar levemente.\n\n"
                "Porque essa é a primeira vez desde o arquivo que alguém realmente parece reconhecer aquilo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 12,
        },
        2: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 1B\n"
                "“Aquilo que pode ser explicado” (Rota Sol)\n"
                "╔══════════════════════════════╗\n"
                "        CAPÍTULO 2\n"
                "   “Aquilo que pode ser explicado”\n"
                "╚══════════════════════════════╝\n"
                "Sol continua cercado por telas e informações quando Gaia se aproxima. Relatórios abertos, padrões sendo cruzados, dezenas de dados passando rápido demais para qualquer pessoa acompanhar naturalmente. Mas ele acompanha. Sempre acompanhou.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia para ao lado da mesa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sem olhar para ela, Sol fala:\n\n"
                "— “Algo saiu do comportamento esperado.”\n\n"
                "Não é pergunta.\n\n"
                "É constatação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia cruza os braços.\n\n"
                "— “Você sempre recebe as pessoas assim?”\n\n"
                "— “Só quando elas chegam diferentes.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Agora ele olha para ela.\n\n"
                "E, por um instante, Gaia sente como se estivesse sendo analisada junto com todas as outras informações da sala.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “O que aconteceu?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela pega o celular devagar e mostra a tela.\n\n"
                "O símbolo continua ali.\n\n"
                "O olho incompleto.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sol não reage emocionalmente.\n\n"
                "Mas a atenção dele muda imediatamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele aproxima a tela do rosto.\n\n"
                "Observa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E então fala algo que faz Gaia sentir um desconforto imediato:\n\n"
                "— “Isso já apareceu antes.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Silêncio.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia responde mais rápido do que pretendia:\n\n"
                "— “Onde?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sol demora alguns segundos.\n\n"
                "Tempo demais.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Em casos que terminaram mal.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 13,
        },
        3: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 1C\n"
                "“Aquilo que alguém percebe antes de você dizer” (Rota Ikarus)\n"
                "╔══════════════════════════════╗\n"
                "        CAPÍTULO 2\n"
                " “Aquilo que alguém percebe antes de você dizer”\n"
                "╚══════════════════════════════╝\n"
                "Gaia demora alguns segundos para responder. Não porque não saiba o que dizer, mas porque a pergunta dele desmonta algo dentro dela.\n\n"
                "“Você também sentiu?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Não foi surpresa.\n\n"
                "Não foi medo.\n\n"
                "Não foi curiosidade.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Foi reconhecimento.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus continua olhando para ela em silêncio. Não pressionando. Não esperando resposta imediata. Apenas presente. O caderno fechado permanece sob uma de suas mãos, como se ele tivesse interrompido algo importante no instante em que ela se aproximou.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia finalmente pergunta:\n\n"
                "— “Você sabe do que eu tô falando?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus inclina levemente a cabeça.\n\n"
                "— “Não.”\n\n"
                "A resposta vem rápida demais para ser mentira.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Mas ele continua:\n\n"
                "— “Só sei que alguma coisa mudou quando você entrou aqui.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o corpo ficar mais atento imediatamente.\n\n"
                "Não exatamente desconforto.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "É a sensação de estar perto de alguém que percebe detalhes demais.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela observa o caderno sobre a mesa.\n\n"
                "Anotações feitas à mão.\n\n"
                "Palavras riscadas.\n\n"
                "Frases incompletas.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia pergunta:\n\n"
                "— “Por que você escreve isso tudo?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus olha rapidamente para o caderno antes de responder:\n\n"
                "— “Porque memória falha.”\n\n"
                "Uma pausa curta.\n\n"
                "— “E sensação desaparece rápido demais.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então o celular vibra novamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Os dois olham ao mesmo tempo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A tela acende sozinha.\n\n"
                "Apenas o símbolo.\n\n"
                "O olho incompleto.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E, dessa vez—\n\n"
                "Ikarus vê também.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O pequeno sorriso desaparece.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Isso definitivamente não é normal.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 6,
        },
        4: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 4\n"
                "“Aqueles que Não Desviam o Olhar”\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "As luzes da Ordem falham violentamente por alguns segundos.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Não o suficiente para causar pânico.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Mas o bastante para destruir qualquer sensação de normalidade que ainda restava.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Conversas param.\n"
                "Telas piscam.\n"
                "Celulares vibram ao mesmo tempo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o corpo travar antes mesmo de olhar para a própria tela.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Porque agora ela sabe.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Isso não está acontecendo só com ela.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ao redor, agentes começam a reagir.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Que merda é essa?”\n\n"
                "— “Meu celular abriu sozinho.”\n\n"
                "— “Tem alguma imagem aqui.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Mas nem todos conseguem ver.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E isso é o pior.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Algumas pessoas olham para os próprios celulares sem reação nenhuma.\n\n"
                "Como se absolutamente nada estivesse aparecendo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A tela principal da Ordem liga sozinha.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Estática.\n\n"
                "Ruído.\n\n"
                "Imagem falhando.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então—\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "uma filmagem começa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Não parece gravação comum.\n\n"
                "Parece… observação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A câmera atravessa lentamente um corredor escuro iluminado apenas por velas. Máscaras penduradas nas paredes observam a passagem da filmagem. Máscaras negras, lisas, sem expressão, semelhantes ao rosto vazio de alguma entidade esquecida.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então eles aparecem.\n\n"
                "Pessoas paradas ao redor de uma mesa longa.\n\n"
                "Todas usando máscaras negras.\n\n"
                "Nenhuma delas olha para a câmera.\n\n"
                "Porque todas já estavam olhando antes dela chegar.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Uma voz começa.\n\n"
                "Distorcida.\n\n"
                "Mas calma demais para parecer humana.\n\n"
                "— “Nós observamos aqueles que ainda desviam.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A imagem falha rapidamente.\n\n"
                "Por um frame—\n\n"
                "Gaia vê algo sobre a mesa.\n\n"
                "Um objeto.\n\n"
                "Pequeno.\n\n"
                "Mas errado.\n\n"
                "Uma mão humana.\n\n"
                "Transformada em porcelana negra.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A voz continua:\n\n"
                "— “Toda alma deixa algo para trás.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Outro corte.\n\n"
                "Mais objetos aparecem rapidamente na tela:\n\n"
                "Um relógio pulsando como um coração.\n\n"
                "Um olho humano preso dentro de vidro.\n\n"
                "Uma máscara respirando lentamente.\n\n"
                "— “Nós chamamos isso de Legado.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o estômago apertar.\n\n"
                "Porque aquilo não parece coleção.\n\n"
                "Parece preservação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A câmera finalmente mostra o centro da sala.\n\n"
                "Existe alguém sentado lá.\n\n"
                "Imóvel.\n\n"
                "Usando uma máscara diferente das outras.\n\n"
                "Mais longa.\n\n"
                "Mais escura.\n\n"
                "Sem abertura para os olhos.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A figura ergue lentamente a cabeça.\n\n"
                "E, pela primeira vez—\n\n"
                "olha diretamente para a câmera.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A voz finaliza:\n\n"
                "— “Aqueles que desviam o olhar esquecem.”\n\n"
                "Uma pausa.\n\n"
                "— “Aqueles que observam… permanecem.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A transmissão falha violentamente.\n\n"
                "Todas as luzes se apagam.\n\n"
                "No escuro—\n\n"
                "o celular de Gaia vibra novamente.\n\n"
                "Uma nova mensagem aparece.\n\n"
                "“Ikarus: precisamos conversar. Agora.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Para resolver o próximo bloco, use a imagem: https://imgur.com/a/FFHgO6Z\n\n"
                "Digite sua resposta."
            ),
            "requires_answer": [
                "A estação não está abandonada.",
                "Alguém esteve lá recentemente."
            ],
            "answer_failure_text": "Resposta incorreta. Tente novamente.",
            "next": 5,
        },
        5: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 5\n"
                "“Aquilo que precisa ser encontrado”\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia atravessa os corredores da Ordem mais rápido do que percebe. O ambiente ao redor continua agitado depois da transmissão, agentes falando ao mesmo tempo, telas sendo analisadas, ordens cruzando pelos setores — mas tudo parece distante agora.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Porque uma coisa ficou clara.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Isso não foi uma ameaça.\n\n"
                "Foi um convite.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela encontra Ikarus na área externa da Ordem, perto das escadas metálicas que levam ao estacionamento inferior. A chuva caiu em algum momento sem que ela percebesse. Fraca. Constante. O reflexo das luzes no chão molhado faz o lugar parecer silencioso demais para aquela hora.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus está parado perto da grade.\n\n"
                "O caderno continua nas mãos dele.\n\n"
                "Mas agora—\n\n"
                "existem anotações novas.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia desacelera os passos.\n\n"
                "— “Você viu aquilo.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus não responde imediatamente.\n\n"
                "Ele continua olhando a chuva.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então fala:\n\n"
                "— “Eu já ouvi esse nome antes.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente a atenção aumentar imediatamente.\n\n"
                "— “Aqueles que Não Desviam o Olhar?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus finalmente olha para ela.\n\n"
                "— “Não oficialmente.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele abre o caderno em algumas páginas específicas.\n\n"
                "Desenhos.\n\n"
                "Símbolos.\n\n"
                "Frases soltas.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E então—\n\n"
                "uma página inteira preenchida pela mesma frase:\n\n"
                "“Legados não são criados. São deixados.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente um desconforto imediato.\n\n"
                "Porque aquilo não parece anotação.\n\n"
                "Parece memória.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus continua:\n\n"
                "— “Eu comecei a escrever isso semanas atrás.”\n\n"
                "Uma pausa curta.\n\n"
                "— “Sem saber o porquê.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia cruza os braços lentamente.\n\n"
                "— “Então o culto tá ligado ao símbolo.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Mais do que isso.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus fecha o caderno.\n\n"
                "— “Acho que eles querem ser encontrados.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O silêncio que vem depois dura pouco.\n\n"
                "Porque o celular de Gaia vibra novamente.\n\n"
                "Uma nova imagem aparece.\n\n"
                "Uma fotografia antiga.\n\n"
                "Uma estação de metrô abandonada.\n\n"
                "Na parte inferior da imagem—\n\n"
                "coordenadas.\n\n"
                "E uma frase.\n\n"
                "“Encontre o primeiro Legado.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "❖ MECÂNICA DE INVESTIGAÇÃO\n\n"
                "A partir deste momento, algumas partes da história conterão enigmas, códigos, frases ocultas e pistas espalhadas nos textos, imagens e diálogos.\n\n"
                "Nem todas as respostas estarão explícitas.\n\n"
                "Algumas precisarão ser interpretadas.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "❖ COMO FUNCIONA\n\n"
                "— Você deverá analisar pistas e responder corretamente para avançar em certas partes.\n\n"
                "— Algumas respostas podem alterar relações, status ou caminhos da história.\n\n"
                "— Certas pistas podem aparecer muito antes da resposta ser necessária.\n\n"
                "— Nem tudo é confiável.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "❖ IMPORTANTE\n\n"
                "Quando houver um puzzle, responda normalmente no chat.\n\n"
                "Exemplo:\n"
                "“Resposta: estação”\n"
                "ou\n"
                "\"A senha é 213\"\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "❖ PRIMEIRO OBJETIVO\n\n"
                "A fotografia possui algo estranho.\n\n"
                "Algo que não deveria estar ali.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Observe com atenção:\n\n"
                "“Por que existe luz na estação… se ela está abandonada há mais de dez anos?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar para seguir."
            ),
            "next": 10,
        },

        10: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 6\n"
                "“O Primeiro Legado”\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ikarus permanece olhando para a fotografia por alguns segundos depois da resposta de Gaia.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "“A estação não está abandonada.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ele não sorri.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Mas Gaia percebe algo próximo disso.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Reconhecimento.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "— “Então você percebeu também.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia volta a observar a imagem. Agora que a resposta existe, fica impossível ignorar. As luzes funcionando. Reflexos recentes no chão molhado. A pequena janela iluminada ao fundo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Alguém ainda usa aquele lugar.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ou algo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ikarus pega o celular da mão dela cuidadosamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Então amplia a parte inferior da fotografia.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia franze levemente a testa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Porque existe mais alguma coisa ali.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Quase invisível.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Uma silhueta parada perto dos trilhos.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Imóvel.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Observando diretamente a câmera.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Mas isso não é o pior.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "O pior é o formato do corpo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Errado demais.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Os braços parecem longos demais.\n\n"
                "O pescoço inclinado em um ângulo impossível.\n\n"
                "E a pele…\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "não parece pele.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Parece porcelana rachada.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia sente um arrepio subir lentamente pela nuca.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ikarus fala baixo:\n\n"
                "— “Acho que esse é um Legado.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Silêncio.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "A palavra pesa diferente agora.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Porque deixou de ser conceito.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Agora tem forma.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "O celular vibra novamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Nova mensagem.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "“OBJETIVO ATUALIZADO”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "A fotografia desaparece.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Uma nova imagem surge.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Um mapa do metrô.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Grande parte das linhas foi rasurada em vermelho.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Menos uma.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "LINHA 4.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Abaixo dela:\n\n"
                "“Os que desviam se perdem.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Outra frase aparece lentamente.\n\n"
                "“Encontre a plataforma correta.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "❖ NOVO PUZZLE\n\n"
                "O mapa possui uma inconsistência.\n\n"
                "Algo impossível para uma linha de metrô abandonada há mais de dez anos.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Observe a imagem e descubra:\n\n"
                "❖ O que indica que os trilhos ainda estão sendo utilizados?\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Digite sua resposta."
            ),
            "requires_answer": [
                "Linha 4",
            ],
            "answer_failure_text": "Resposta incorreta. Tente novamente.",
            "next": 11,
        },

        11: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 7\n"
                "“A Plataforma 7”\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ikarus permanece olhando para o mapa por alguns segundos depois da resposta de Gaia.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "“A Linha 4 ainda está sendo usada.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "A chuva continua caindo atrás deles, refletindo as luzes frias da Ordem no chão molhado. Mas agora o ambiente parece distante demais. Pequeno demais.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Porque alguma coisa acabou de deixar de ser teoria.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ikarus aproxima lentamente a imagem do mapa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Os dedos dele passam pelas estações da Linha 4.\n\n"
                "Vale Sereno.\n\n"
                "Santa Brígida.\n\n"
                "Manancial.\n\n"
                "Orfanato.\n\n"
                "Penitenciária.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Então ele para.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "“Plataforma 7.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia sente um desconforto imediato.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Porque aquela estação é diferente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Não existe conexão.\n\n"
                "Não existe continuação.\n\n"
                "Não existe saída marcada.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ela simplesmente…\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "termina.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ikarus fala baixo:\n\n"
                "— “Essa estação não deveria existir.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia franze levemente a testa.\n\n"
                "— “Como assim?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ele vira o caderno rapidamente até encontrar uma página específica.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Um desenho antigo do mapa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Mais antigo que a imagem do celular.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "E, nele—\n\n"
                "a Plataforma 7 não existe.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "O silêncio pesa imediatamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Porque isso significa uma coisa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "A estação foi adicionada depois.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Mas ninguém constrói uma estação secreta em uma linha abandonada.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "O celular vibra novamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Nova mensagem.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "“Os que observam encontram.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Outra surge logo abaixo.\n\n"
                "“Último trem: 02:13”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia sente o estômago apertar.\n\n"
                "O mesmo horário da carta.\n\n"
                "Da igreja.\n\n"
                "Dos relatos.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Ikarus guarda o caderno lentamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Então olha diretamente para Gaia.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Pela primeira vez desde que tudo começou—\n\n"
                "ele parece decidido.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "— “Se a Plataforma 7 existe…”\n\n"
                "Uma pausa curta.\n\n"
                "— “Então é lá que os Legados começam.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Silêncio.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "A chuva aumenta do lado de fora.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "E, naquele instante—\n\n"
                "Gaia percebe uma coisa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Eles não estão investigando um culto.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Estão seguindo um caminho que alguém preparou para eles.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Fim do Capítulo 2"
            ),
            "next": None,
        },

        6: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 2C\n"
                "Ikarus continua olhando para o símbolo na tela. O silêncio entre os dois não parece desconfortável, mas também não é normal. Gaia percebe isso rápido. Ele não está reagindo como alguém que viu algo estranho.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Está reagindo como alguém que reconheceu uma sensação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Você já viu isso antes?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia pergunta sem tirar os olhos dele.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus demora um pouco para responder.\n\n"
                "Não por hesitação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Mas porque parece organizar algo na própria cabeça.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Não exatamente.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele apoia os dedos sobre o caderno fechado.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Mas eu já sonhei com isso.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente um arrepio imediato.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus continua antes que ela pergunte:\n\n"
                "— “Não o símbolo.”\n\n"
                "Uma pausa curta.\n\n"
                "— “A sensação.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele olha diretamente para ela agora.\n\n"
                "— “Como se alguma coisa estivesse esperando eu perceber ela.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O ar parece mais pesado depois disso.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia tenta racionalizar imediatamente.\n\n"
                "Coincidência.\n\n"
                "Influência.\n\n"
                "Sugestão.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Mas nenhuma das três parece suficiente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus pega o próprio caderno e abre algumas páginas rapidamente.\n\n"
                "Anotações.\n\n"
                "Frases incompletas.\n\n"
                "Desenhos tortos.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então ele para em uma página específica.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o corpo travar por um segundo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Porque o símbolo está lá.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Desenhado à mão.\n\n"
                "Muito antes do celular vibrar.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 9,
        },
        12: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 2A\n"
                "“Aquilo que já existia antes de você encontrar” (Rota Jaser)\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Jaser continua olhando para o símbolo na tela por tempo demais. Não assustado. Não exatamente preocupado. Mas atento de uma forma que Gaia ainda não tinha visto nele.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele pega o celular da mão dela sem pedir permissão.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O gesto é rápido.\n\n"
                "Natural.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Como se aquilo tivesse importância suficiente para ultrapassar educação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Os olhos dele percorrem lentamente o símbolo.\n\n"
                "O olho incompleto.\n\n"
                "As linhas tortas.\n"
                "Os espaços vazios.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então Jaser pergunta:\n\n"
                "— “Ele falou alguma coisa?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente um leve desconforto imediato.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "“Ele.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Não “isso”.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela responde devagar:\n\n"
                "— “Você conhece isso?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser ignora a pergunta primeiro.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “O que ele disse?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A insistência muda tudo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Porque agora Gaia entende:\n\n"
                "Jaser não está tentando descobrir *o que é*.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Está tentando descobrir *em qual estágio está.*\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela hesita por um instante antes de responder:\n\n"
                "— “Disse que eu demorei.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O silêncio que vem depois dura pouco.\n\n"
                "Mas pesa demais.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser devolve o celular lentamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Então começou.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o corpo ficar tenso imediatamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Começou o quê?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser olha ao redor antes de responder.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Como se estivesse verificando quem poderia ouvir.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Não aqui.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E essa é a primeira vez desde que Gaia encontrou o arquivo…\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "que alguém parece mais preocupado do que ela.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 7,
        },
        13: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 2B\n"
                "“Aquilo que deixa rastros” (Rota Sol)\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Sol continua olhando para o símbolo sem dizer nada por alguns segundos. O reflexo da tela atravessa os óculos dele enquanto diferentes arquivos começam a abrir automaticamente nos monitores ao redor.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia percebe rápido:\n\n"
                "ele já está procurando.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Isso apareceu em quatro casos.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A voz dele permanece calma.\n\n"
                "Linear.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Mas isso não deixa a frase menos pesada.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia se aproxima um pouco mais.\n\n"
                "— “Que casos?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sol move uma das telas para o lado.\n\n"
                "Fotos aparecem.\n\n"
                "Lugares diferentes.\n"
                "Pessoas diferentes.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Mas o símbolo…\n\n"
                "sempre presente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o estômago apertar levemente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Porque aquilo não parece coincidência.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Parece repetição.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sol continua:\n\n"
                "— “Todos começaram iguais.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele finalmente olha para ela.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Mensagem anônima.”\n\n"
                "Uma pausa curta.\n\n"
                "— “Sensação de reconhecimento.”\n\n"
                "Outra pausa.\n\n"
                "— “E comportamento alterado após o primeiro contato.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia cruza os braços sem perceber.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “E como terminaram?”\n\n"
                "Silêncio.\n\n"
                "Sol demora para responder.\n\n"
                "O suficiente para tornar a ausência pior que a resposta.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Desaparecendo.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 8,
        },
        7: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 3A\n"
                "“Aquilo que já escolheu você” (Rota Jaser)\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Jaser começa a andar sem explicar para onde está indo. Gaia acompanha por instinto, ainda segurando o celular com força demais para perceber. Eles atravessam os corredores mais vazios da Ordem até chegarem a uma área antiga do prédio, pouco usada, onde as luzes demoram alguns segundos para acender completamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser para em frente a uma porta metálica.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Eu achei que isso tinha acabado.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A frase sai baixa.\n\n"
                "Mais para ele mesmo do que para Gaia.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ela observa enquanto ele digita uma sequência longa demais para ser apenas uma sala comum. A porta destrava com um ruído seco.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O lugar parece abandonado.\n\n"
                "Arquivos físicos.\n\n"
                "Pastas antigas.\n\n"
                "Fotos presas em quadros de investigação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Tudo coberto por poeira suficiente para denunciar que ninguém entra ali há muito tempo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser caminha direto até uma das mesas.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sem hesitação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Como alguém que já esteve ali muitas vezes.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele abre uma gaveta e tira uma pasta escura.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia percebe imediatamente o símbolo desenhado nela.\n\n"
                "O olho incompleto.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Seu estômago aperta.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “O que é isso?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Jaser permanece alguns segundos em silêncio antes de responder:\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Pessoas que começaram a ver coisas antes de desaparecer.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele abre a pasta.\n\n"
                "Fotografias.\n\n"
                "Anotações.\n\n"
                "Relatórios incompletos.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E todas as páginas têm algo em comum: \n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "A mesma frase.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "“Você demorou.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o corpo gelar lentamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Porque agora—\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "isso deixou de ser individual.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 4,
        },
        8: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 3B\n"
                "“Aquilo que continua aparecendo” (Rota Sol)\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia permanece olhando para as fotografias enquanto Sol continua cruzando arquivos nos monitores. O ambiente ao redor parece menor agora. Mais fechado. Como se cada nova informação reduzisse as possibilidades ao invés de ampliar.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então uma das telas muda.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Automaticamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sol percebe imediatamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "As mãos dele param sobre o teclado.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia olha para a tela.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Uma câmera de segurança foi aberta sozinha.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Corredor principal da Ordem.\n\n"
                "Ao vivo.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Vazio.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Por alguns segundos, nada acontece.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então a imagem falha.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Pequenos cortes.\n\n"
                "Ruídos.\n\n"
                "Distorções rápidas.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E, por um único frame—\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "o símbolo aparece refletido na câmera.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Grande demais.\n\n"
                "Perto demais.\n\n"
                "Como se estivesse atrás do observador.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente um arrepio imediato.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sol fecha a janela rapidamente.\n\n"
                "Rápido demais.\n\n"
                "Quase nervoso.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E isso assusta mais do que a imagem.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Porque Sol não reage assim.\n\n"
                "Nunca.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele respira fundo antes de falar:\n\n"
                "— “Ele não deveria conseguir entrar aqui.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente o desconforto crescer imediatamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Ele?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Sol olha novamente para a tela apagada.\n\n"
                "E responde:\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Agora eu tenho certeza.”\n\n"
                "Uma pausa curta.\n\n"
                "— “Você não recebeu uma mensagem.”\n\n"
                "Silêncio.\n\n"
                "— “Você foi encontrada.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 4,
        },
        9: {
            "text": (
                "📖✨ CAPÍTULO 2 — BLOCO 3C\n"
                "“Aquilo que aparece antes da memória” (Rota Ikarus)\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n"
                "Gaia permanece olhando para o desenho no caderno. O símbolo está ali, imperfeito, feito à mão, mas inconfundível. As mesmas linhas incompletas. O mesmo formato impossível de ignorar.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus fecha o caderno lentamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Como se já soubesse que mostrar aquilo mudaria alguma coisa.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Eu desenhei isso faz semanas.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia finalmente olha para ele.\n\n"
                "— “Como?”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus solta um pequeno ar pelo nariz, quase uma risada sem humor.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Queria saber.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ele passa a mão pelas páginas do caderno.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "— “Eu comecei a sonhar com corredores que não existem.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Outra pausa.\n\n"
                "— “E sempre tinha alguém olhando.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Gaia sente a tensão aumentar devagar.\n\n"
                "Porque, pela forma que ele fala…\n\n"
                "isso não parece imaginação.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Ikarus pega o celular da mão dela cuidadosamente.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O símbolo permanece na tela.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Então ele faz algo estranho.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Encosta o símbolo desenhado no caderno ao símbolo do celular.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "E, por um segundo—\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "a tela reage.\n\n"
                "Não com imagem.\n\n"
                "Não com som.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Mas com uma frase.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "“FINALMENTE.”\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "O celular vibra violentemente.\n\n"
                "E as luzes da sala apagam no mesmo instante.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "Digite /continuar"
            ),
            "next": 4,
        },
    },
}

ATTRIBUTE_LABELS = {
    "razao": "Razão",
    "emocao": "Emoção",
    "vazio": "Vazio",
    "investigacao": "Investigação",
    "acao": "Ação",
}


def determine_final(attributes: Dict[str, int]) -> str:
    """Determine the final based on dominant attribute."""
    if not attributes:
        return "Indefinido"
    
    dominant = max(attributes.items(), key=lambda x: x[1])
    finals = {
        "razao": "O Observador",
        "emocao": "O Conectado",
        "vazio": "O Liberto",
        "investigacao": "O Investigador",
        "acao": "O Agente",
    }
    return finals.get(dominant[0], "Indefinido")